### PR TITLE
Muon Veto cut added

### PR DESCRIPTION
**Pull request by molinario**
The Muon Veto cut has been added to the list of cuts in sciencerun0.py. It checks the distance in time (ns) between a reference position inside the waveform and the nearest MV trigger (which is determined with respect to the center of the event). The event is excluded if the nearest MV trigger falls in a [-1ms,+10us] time window with respect to the reference position. It requires Proximity minitrees.

https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:mv_xe1t:syncro_with_muons

### CODE REVIEW

**Comment by tunnell** [comment]
Thanks @molinario .  Can you implement this as a StringLichen (see examples) just to clean it up a bit?  It's already quite clean but it helps us in the longerterm.

**Comment by tunnell** [comment]
@molinario ?

**Review by tunnell — CHANGES_REQUESTED** [review]
Can you implement this as a StringLichen (see examples) just to clean it up a bit? It's already quite clean but it helps us in the longerterm.

**Comment by molinario** [comment]
I implemented it as a StringLichen. Let me know if something is wrong with this.

**Review by pdeperio — CHANGES_REQUESTED** [review]
Should this be officially added to the [AllEnergy list](https://github.com/XENON1T/lax/blob/v1.0.0/lax/lichens/sciencerun0.py#L36)?

How about [sciencerun1.py](https://github.com/XENON1T/lax/blob/v1.0.0/lax/lichens/sciencerun1.py#L184)?  Can this be inherited or does it need to be retuned?

Also, MC is using lax as well through ```laxer```.  I guess this cut would not be applicable, so could you add it to the list of cuts to ignore [here](https://github.com/XENON1T/lax/blob/v1.0.0/bin/laxer#L89)?

**Comment by molinario** [comment]
@pdeperio 
1. I think it should be added to AllEnergy list
2. We are working on fine tuning of the cut for science run 1
3. Ok

**Comment by molinario** [comment]
@pdeperio 
For some reason I can't modify the "list of cut to be ignored". I try to switch to the branch "add-mv-cut-3", but it goes to a non existing page. Maybe you can do this?

**Comment by pdeperio** [comment]
OK I've done all, except just inherited SR0 definition into SR1, so you should replace when ready.  (For ```laxer```, needed to merge master into your branch.)

**Comment by molinario** [comment]
@pdeperio Ok thanks.

**Comment by pdeperio** [comment]
@tunnell can you approve your review?

@molinario any update on the tuning?

**Review by tunnell — APPROVED** [review]

**Comment by molinario** [comment]
New version of MV cut for Science Run 1 has been added to sciencerun1.py. The event is excluded if the nearest MV trigger falls in a [-2ms,+3ms] time window with respect to the reference position. It requires Proximity minitrees.
https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:analysis:mv_cut_sr1

**Review by pdeperio — CHANGES_REQUESTED** [review]
Should SR0 be the same as SR1?

**Comment by molinario** [comment]
I would say yes. 

One thing I don't know is if the Proximity minitrees for Science Run 0 are redone with new hax version, or not. This is because we changed the definition of nearest_muon_veto_trigger in the Proximity treemaker at point.

**Comment by pdeperio** [comment]
Yes, hax and cax should treat SR0 files the same, so as long as the treemaker version was incremented, which I see it was in https://github.com/XENON1T/hax/pull/125, then those minitrees should have been regenerated. Could you please double check by re-running your analysis on ```_sciencerun0``` tag? Then if all good, can move this cut definition into ```sciencerun0.py``` and inherit in ```sciencerun1.py``` like before.

**Comment by molinario** [comment]
Ok, I will do this.

**Comment by molinario** [comment]
I repeated the analysis for the definition of MV cut on _sciencerun0 tagged runs. The results are here:
https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:analysis:mv_cut_sr1#can_we_use_the_same_cut_for_science_run_0

They show that we can extend the SR1 cut definition to SR0.

**Review by pdeperio — APPROVED** [review]

**Review by sreichard — APPROVED** [review]

**Pull request merged**
