### PR TITLE
S2 Single Scatter

### PR DESCRIPTION
**Pull request by zhut19**
Added S2SingleScatter

### CODE REVIEW

**Comment by tunnell** [comment]
Can you add a link to your note?

Also, is the cut over all energy ranges approach the low-energy form in some limit?

**Comment by tunnell** [comment]
Also, I don't think the code will work as it is.  You redefine the same class twice.  Also, to fetch methods in another class, you have to do e.g. S2Width.function().  See the S2Width example.  I'll see if I can tweak it.  Thanks for this!

**Review by tunnell — CHANGES_REQUESTED** [review]
Please also add S2SingleScatterSimple with your linear requirement

**Comment by zhut19** [comment]
I have updated it, so there is a S2SingleScatter(Lichen) is a combination of two linear function that work for full range.
And there is a S2SingleScatterSimple(Lichen) which is only the lower energy part one of the two linear function. Works up to s2 < 20000 pe

But only the full range one is in AllCuts(manyLichen)

**Review by tunnell — APPROVED** [review]

**Comment by tunnell** [comment]
Please add link to note and your contact info (like others), then I can merge.

**Pull request merged**
