### PR TITLE
s2width_HE 

### PR DESCRIPTION
**Pull request by chiaracapelli**
change connection between low and high energy cut from 250 keV to 200 keV to solve issue https://github.com/XENON1T/lax/issues/192#issue-682628312

### CODE REVIEW

**Comment by cwittweg** [comment]
Chiara checked with Tim. This should not make problems.

**Comment by cwittweg** [comment]
- [ ]

**Comment by cwittweg** [comment]
Sorry, clicked the wrong button. Chiara checked with Tim. The change should not make any problems.

**Review by cwittweg — APPROVED** [review]
Looks good. There is a 200 now where there was a 250.

**Comment by chiaracapelli** [comment]
Acceptance of HE cut below 250 keV would create a even bigger drop

**Pull request closed without merging**
