### PR TITLE
Add LargestPeakProperties treemaker to laxer

### PR DESCRIPTION
**Pull request by pdeperio**
Update laxer (used in OSG MC production) according to all the recent changes.

### CODE REVIEW

**Comment by pdeperio** [comment]
@jpienaar13 @pietrodigangi Could you (MC group) please check if this is still working in full chain?

**Comment by coderdj** [comment]
@jpienaar13 @pietrodigangi  did you check if this works?

Otherwise @pdeperio we can just merge to get off the docket and they will see if it breaks things. ;-)

**Comment by jpienaar13** [comment]
@pdeperio @coderdj 

So adding in the FlashIdentification minitrees does break this for MC. Simply removing it from the list of minitrees solves this problem again. Since we do not simulate Flashes this should be sufficient. However, I checked in the latest lax version and noticed FlashIdentification is not included. Do we still intend to include it? 

In addition the new PositionReconstruction minitree does not work for MC data. Looking at that tree, I see a bunch of variables we would need for laxer. So I guess here we have to actually fix the minitree...

**Comment by jpienaar13** [comment]
Nevermind. I had a typo. PosRec works for MC as well

**Comment by jpienaar13** [comment]
I believe #135 makes this obsolete

**Comment by pdeperio** [comment]
```master``` is working without ```LargestPeakProperties```?

**Comment by jpienaar13** [comment]
Didn't check it without. I missed that that was also new in this PR

**Comment by tunnell** [comment]
This obsolete as @jpienaar13 says?

**Comment by pdeperio** [comment]
just adding ```LargestPeakProperties``` still

**Comment by jpienaar13** [comment]
Let me test again quickly. I remember it working at the time, but rather safe than sorry.

**Comment by jpienaar13** [comment]
Confirmed that it works

**Review by jpienaar13 — APPROVED** [review]

**Pull request merged**
