### PR TITLE
S2PatternLikelihood Cut Tuning

### PR DESCRIPTION
**Pull request by zhut19**
This update deals with the issue that in SR1 S2PatternLikelihood acceptance decreased and required returning.

### CODE REVIEW

**Comment by feigaodm** [comment]
@zhut19 better to put a plot, link here for reference

**Review by pdeperio — CHANGES_REQUESTED** [review]
Shouldn't this go in SR0?  i.e. cut should be applicable for both SRs.

**Comment by feigaodm** [comment]
@pdeperio Shouldn't likelihood values depends on dof, ie number of channels on top (and revieving the hits)? Then it could be run-dependent. Maybe it's a second order effect if we are not loosing PMT so frequently.

**Comment by pdeperio** [comment]
True.  Then if we're changing how the cut is tuned, it should also be applied to SR0 for consistency, right?

**Comment by zhut19** [comment]
As mentioned above we fit the 95% below the bump and 98% above the bump as show 
1a
1b
And we got a very close form of the percentile line, and this effect is also shown in acceptance plot below. as the cut stick to 98% once go above 120 pe
1c

**Review by pdeperio — APPROVED** [review]

**Review by sreichard — APPROVED** [review]

**Pull request merged**
