### PR TITLE
Adding S2 pattern likelihood cut for high energy

### PR DESCRIPTION
**Pull request by ctherreau**
Add S2PatternLikelihood for high energy. For SR1 only. 

Include SR1 low energy cut + extension up to 3 MeV. [Acceptance for SR1](https://xe1t-wiki.lngs.infn.it/lib/exe/detail.php?id=xenon%3Axenon1t%3Achloetherreau%3A0vbb_s2_likelihood_cut_he_update&media=xenon:xenon1t:chloetherreau:upd2_s2patternhe_acc_ces.png)

[See this note for more details](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:chloetherreau:0vbb_s2_likelihood_cut_he_update#update_s2_pattern_likelihood_cut_at_high_energy_with_position_dependance )

### CODE REVIEW

**Review by JelleAalbers — COMMENTED** [review]
Thanks for the update Chloé. How does this cut relates to @jingqiangye's cut defined slightly earlier in the file? I understand it is made to be better at higher energies, but is it equal at lower energies or different? If they are different, which one would you recommend to use for which regions of cS2?

**Comment by ctherreau** [comment]
Hi Jelle, this cut is defined in two regions : 

  - S2 < 1e4 PE = no change compare to [SR1's cut](https://github.com/XENON1T/lax/blob/master/lax/lichens/sciencerun1.py#L246)  
  - S2 > 1e4 PE = new definition as presented in the note link above.

I didn't include @jingqiangye's cut. 

I would recommend to use this cut when one want to look at all ER energy range (up to 3 MeV).

**Review by JelleAalbers — APPROVED** [review]
Thanks, so like Jingqiang's cut (https://github.com/XENON1T/lax/pull/153), it is identical to the old SR1 cut for low-energy analyses. Your cut extends to higher energies (3 MeV) than Jingqiang's (220 keV). 

@jingqiangye any comments? Would you consider Chloe's cut also for the range 1e4 PE - 220 keV, or does your cut have an advantage there? If not, we could replace your cut with hers.

**Comment by jingqiangye** [comment]
Yeah I think we can replace my cut with this cut. I just checked the cut acceptance up to 210 keV with a better granularity, looks good to me.

I just wonder if S2PatternReducedAP treemaker is implemented in hax, or just use the one from [high e analysis](https://github.com/XENON1T/High-Energy-Analysis/blob/master/Cuts/S2PatternLikelihood/S2PatternReducedAP.py)?

**Comment by JelleAalbers** [comment]
Great; @ctherreau, if you agree, could you rename S2PatternLikelihoodHE -> S2PatternLikelihood, and delete the old cut?

**Comment by ctherreau** [comment]
Done

**Review by jingqiangye — APPROVED** [review]
Thanks Chloe. LowER will use your cut instead for SR1.

**Pull request merged**
