### PR TITLE
Muon Veto Cut added to the list of cuts

### PR DESCRIPTION
**Pull request by molinario**
The Muon Veto cut has been added to the list of cuts in sciencerun0.py. It excludes events in coincidence with Muon Veto triggers.

### CODE REVIEW

**Comment by coderdj** [comment]
There's something wrong with this merge. It adds half a million lines of code.

**Comment by molinario** [comment]
Ok, I probably did something wrong when I submitted the pull request (as you can imagine I didn't modify half a million lines of code :-) ). Is it fine to follow these instructions? https://lax.readthedocs.io/en/latest/contributing.html

**Comment by coderdj** [comment]
Actually maybe it's OK. All the changes are in the .tox directory. I have no idea how that works. Maybe someone else has an idea. In general it's impossible to see what was changed in the commit because of all the changes in .tox.

**Comment by molinario** [comment]
I guess is better to create a new pull requests. I could close this one and open a new one starting from scratch.

**Pull request closed without merging**
