### PR TITLE
Update S2Tail cut for SR1

### PR DESCRIPTION
**Pull request by ramirezdiego**
0 < s2_over_tdiff < 0.04   --->   0 < s2_over_tdiff < 0.025

https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:analysis:subgroup:20170720_sr1_cut_s2_tail
https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:analysis:subgroup:cuts:meetings:20170811

### CODE REVIEW

**Review by andrewgrahambrown — COMMENTED** [review]
Looks fine to me

**Comment by ramirezdiego** [comment]
@sreichard ?

**Review by sreichard — CHANGES_REQUESTED** [review]
The first part of this OR logic seems to be redundant. Is it not sufficient to have a single "less than" inequality?

**Review by sreichard — APPROVED** [review]
I approve.

**Comment by pdeperio** [comment]
Wasn't that first part to take care of NaN's?

**Comment by ramirezdiego** [comment]
@pdeperio, yes, but the new TailCut treemaker already takes care of it (see the comment in my last commit). Just in case, I just tested both conditions for ~10 days of SR1 data and they filter exactly the same number of events.

**Comment by ramirezdiego** [comment]
@pdeperio, any other comment?
I think @andrewgrahambrown and @sreichard do not have the rights to merge.

**Comment by pdeperio** [comment]
sorry, thought @sreichard and @andrewgrahambrown already had merge power here.  just added you guys now, can you try?

**Pull request merged**
