### PR TITLE
Addition of CS2AreaFractionTopExtended

### PR DESCRIPTION
**Pull request by DCichon**
See: xenon:xenon1t:double_beta:cs2_aft_extension

### CODE REVIEW

**Review by JelleAalbers — APPROVED** [review]
Thanks Dominic!

This is a replacement for the CS2AreaFractionTop cut to fix its steeply falling acceptance at high energies. It is a very conservative cut that only removes the 1% most extreme outliers from 220Rn calibration data (after a few preselection cuts to remove obvious bad populations). 

Since gas events are easily separable in AFT for S2 >~ few-thousand PE, it would be best to switch to this cut for analyses at higher S2 than our regular WIMP search region. Specifically, for S2 >~ 50 000 PE the old cut's acceptance seems to sinks below 90%. (well, at least its passthrough in Rn data does, but there isn't much gas background in that range in this data)

For low-energy analyses, the cut is also looser than CS2AreaFractionTop. Since gas events are a more important background at low energies, I don't see a reason to switch to this cut for low-energy work. Would you agree @DCichon?

**Comment by DCichon** [comment]
Hi Jelle. I agree with using the extended AFT cut for now only for analyses at higher energies than the SR0/SR1 WIMP region of interest, as the old CS2AreaFractionTop cut is fine otherwise. This is mostly a question about whether CS2AreaFractionTopExtended should completely replace CS2AreaFractionTop in the postsr1 lichen file or not, right?

**Comment by JelleAalbers** [comment]
Good; I was indeed thinking about whether this cut should override the old one or not, so we'll keep it as 'CS2AreaFractionTopExtended'.

**Comment by JelleAalbers** [comment]
In case someone hits the same problem: you cannot use the 'pruned' standardized SR1 data files with this cut, since these do not include the column `s2_lifetime_correction`. The 'unpruned' SR1 files work fine.

**Pull request merged**
