### PR TITLE
Add S2 single scatter for high energy

### PR DESCRIPTION
**Pull request by zhut19**
This is a preliminary cut for multiple s2s for high energy studies, details see wiki note
https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:sim:notes:tzhu:s2singlescatterpostsr1

### CODE REVIEW

**Review by jpienaar13 — APPROVED** [review]

**Comment by chiaracapelli** [comment]
Can you add in the comments from which energy or s2 threshold we should use this cut?

**Comment by zhut19** [comment]
This is only effective for s2 > 1e3, below 1e3 this cut is not able to remove multiple scatters (er). This corresponds to (er) 20 keV, below which multiple scatter rejection drop off rapidly.

**Comment by chiaracapelli** [comment]
Hi, I am testing it but I got error importing lax, first for the unknown pickle and if I import it, then it says is not possible to import the sciencerun1 lichens. The master branch has no problems related to sciencerun1 in import.

**Comment by chiaracapelli** [comment]
Now it works, thanks!

**Review by chiaracapelli — APPROVED** [review]

**Pull request merged**
