### PR TITLE
Fix SingleElectronS2s bug, conditions reversed

### PR DESCRIPTION
**Pull request by pdeperio**
@feigaodm discovery

### CODE REVIEW

**Review by tunnell — APPROVED** [review]

**Comment by tunnell** [comment]
@MAVJ Let us know if this is wrongly interpreted.  You checked outside box instead inside.

**Comment by MAVJ** [comment]
@pdeperio Thank you for fixing the typo of the inverted "<" and ">" signs, indeed should be that way. 
@tunnell I talked to @feigaodm and he pointed out to me that there was an issue with the range of the interpolation function used. I checked and to correct this, the interpolation should be re-define to: 

s1_bound_4 = interpolate.interp1d([0, 0.3, 0.4, 0.5, 0.60, 0.60,1], 
                                               [70, 70, 61, 61,35,0,0], 
                                               fill_value='extrapolate', kind='linear')

meaning that I extended the range of the area top fraction. I think that with this change Fei's triggered error could be fixed, could we give it a try?

**Comment by feigaodm** [comment]
Thanks @MAVJ! The new interplation should work. We @pdeperio @tunnell  should modify it accordingly.

**Comment by tunnell** [comment]
@MAVJ @feigaodm make PR?

**Pull request merged**
