### PR TITLE
AmBe fiducial cut and StringLichen

### PR DESCRIPTION
**Pull request by tunnell**
Also fixed issue with versions in setup.py

@ErikHogenbirk please just see that this cut is the AmBe fiducial that you want.

### CODE REVIEW

**Review by ErikHogenbirk — APPROVED** [review]
I checked it out and added the cuts on R and Z that are also used. Also extended description. I like documentation :)

**Comment by tunnell** [comment]
@ErikHogenbirk Do we really want do cut on R,Z at same time?  I figured this would be a cut that we can apply ontop of many different fiducial volumes.  Let's say we change the fiducial volume, isn't the important cut just the distance part?

**Comment by ErikHogenbirk** [comment]
Sure, this is possible. In that case, I'd propose to rename to DistanceToAmBe or something, and make another Lichen that does implement all these at the same time? Otherwise it's still not clear what the AmBe volume actually is (regardless of whether it'll change or not). I would not like to have to apply both the 1T cylinder and AmBe at the same time, would change the volume and perhaps cause confusion.

**Comment by tunnell** [comment]
thanks

**Pull request merged**
