### PR TITLE
S2 width he

### PR DESCRIPTION
**Pull request by WolfXeHD**
I derived a cut to reject events with an unphysical small or large S2 width. In order to do so, I computed the 1% and 99% quantiles of the binned distribution in the space s2_range_50p_area vs drift_time. More details can be found in the description of the lichen and the corresponding note.

### CODE REVIEW

**Comment by chiaracapelli** [comment]
Hi,  you left the default message, can you edit the comment with a short description of the cut?

**Comment by chiaracapelli** [comment]
Hi, I tested the branch with my LAX version and it works.

Is the threshold 200 keV or 250 keV? In the code is 250 keV but in the comment is mentioned that the sample is from 200 keV. Is this only the data sample from which you got the quantiles but then you discard the ones from 200 to 250 and use the low energy S2Width?

**Comment by WolfXeHD** [comment]
Hi Chiara,
the sample based on which I derive the quantiles is a background sample with the cuts mentioned in the note. The energy range in which the quantiles are derived is from 200keV to 3MeV. 

The combination with the existing low energy S2Width cut is done at the at 250keV, i.e. below 250keV the cut is identical with the existing S2Width cut and above the derived quantiles are applied. This is done to keep a flat and high efficiency at low energies and at higher energies.

Cheers,
Tim

**Review by chiaracapelli — APPROVED** [review]

**Review by feigaodm — APPROVED** [review]

**Comment by feigaodm** [comment]
@jpienaar13  and @sreichard , we think it's ready to be merged for use in highE analysis

**Pull request merged**
